# compose.yaml
# Defines a full environment for the SauceNAO bot.

services:
  app:
    build:
      context: src
      dockerfile: Dockerfile
    environment:
      # PORT:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 80
      APP__APPLICATIONURL:
      APP__SUPPORTCHATINVITATIONLINK:
      CONNECTIONSTRINGS__DEFAULT: # "Server=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      # CONNECTIONSTRINGS__CACHE: "redis:6379"
      TELEGRAMBOT__BOTTOKEN:
      # TELEGRAMBOT__WEBHOOKURL: ${APP__APPLICATIONURL}
      # TELEGRAMBOT__SECRETTOKEN:
      # TELEGRAMBOT__SERVERADDRESS: http://local-bot-api-server:8081
      FILES__FFMPEGPATH:
    ports:
      - ${PORT:-80}:80
    # depends_on:
    #   - db
    #   - cache
    #   - local-bot-api-server

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: snao_user
  #     POSTGRES_DB: snao
  #     POSTGRES_PASSWORD:
  #     POSTGRES_HOST_AUTH_METHOD: scram-sha-256
  #   volumes:
  #     - data:/var/lib/postgresql

  # local-bot-api-server:
  #   build: local-server
  #   environment:
  #     TELEGRAM_API_ID:
  #     TELEGRAM_API_HASH:

  # cache:
  #   image: valkey/valkey:latest
  #   environment:
  #     VALKEY_EXTRA_FLAGS: "--maxmemory 512mb --maxmemory-policy allkeys-lru"
  #   ports:
  #     - ${VALKEY_PORT:-6379}:6379
# volumes:
#   data:
