// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SauceNAO.Infrastructure.Data;

#nullable disable

namespace SauceNAO.Infrastructure.Migrations
{
    [DbContext(typeof(SnaoDbContext))]
    partial class SnaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SauceNAO.Core.Entities.ChatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language_code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("ChatId")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_chat_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("SauceNAO.Core.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.Property<string>("FileUniqueId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_unique_id");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer")
                        .HasColumnName("media_type");

                    b.Property<string>("MimeType")
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<string>("ThumbnailFileId")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_file_id");

                    b.Property<string>("ThumbnailMimeType")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_mime_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Sauces", "SauceNAO.Core.Entities.MediaFile.Sauces#Sauce", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Author");

                            b1.Property<string>("Characters");

                            b1.Property<string>("EstimationTime");

                            b1.PrimitiveCollection<string>("Links")
                                .IsRequired();

                            b1.Property<string>("Material");

                            b1.Property<string>("Part");

                            b1.Property<float>("Similarity");

                            b1.Property<string>("Title");

                            b1.Property<string>("Year");

                            b1
                                .ToJson("sauces")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_media_files");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("ix_media_files_file_id");

                    b.HasIndex("FileUniqueId")
                        .IsUnique()
                        .HasDatabaseName("ix_media_files_file_unique_id");

                    b.ToTable("media_files", (string)null);
                });

            modelBuilder.Entity("SauceNAO.Core.Entities.UserAggregate.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_api_keys_owner_id");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("SauceNAO.Core.Entities.UserAggregate.SearchRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<float>("Similarity")
                        .HasColumnType("real")
                        .HasColumnName("similarity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_search_records");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_search_records_media_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_search_records_user_id");

                    b.ToTable("search_records", (string)null);
                });

            modelBuilder.Entity("SauceNAO.Core.Entities.UserAggregate.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<bool>("HasStartedDm")
                        .HasColumnType("boolean")
                        .HasColumnName("has_started_dm");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language_code");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("UseFixedLanguage")
                        .HasColumnType("boolean")
                        .HasColumnName("use_fixed_language");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SauceNAO.Core.Entities.UserAggregate.ApiKey", b =>
                {
                    b.HasOne("SauceNAO.Core.Entities.UserAggregate.UserEntity", "Owner")
                        .WithMany("ApiKeys")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SauceNAO.Core.Entities.UserAggregate.SearchRecord", b =>
                {
                    b.HasOne("SauceNAO.Core.Entities.MediaFile", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_search_records_media_files_media_id");

                    b.HasOne("SauceNAO.Core.Entities.UserAggregate.UserEntity", "User")
                        .WithMany("SearchHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_search_records_users_user_id");

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SauceNAO.Core.Entities.UserAggregate.UserEntity", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("SearchHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
