# /etc/nginx/conf.d/tbas.conf
server {
    listen 80 default_server;

    location ~ /file/bot(\d+:[\w-]+)/(\w+)($|/.*) {
        alias /data/$1/$2$3;
        sendfile on;
    }

    location / {
        proxy_pass http://localhost:8081/;
    }

    gzip on;

    error_log /var/log/nginx/tbas_error.log;
    access_log /var/log/nginx/tbas_access.log;
}
