//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SauceNAO.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SauceNAO.Core.Resources.BotMessages", typeof(BotMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bot provides you with an interface to use &lt;a href=&quot;https://saucenao.com/&quot;&gt;SauceNAO&lt;/a&gt;&apos;s reverse image search engine.
        ///Send me an image (image, GIF or a sticker) and I&apos;ll try to reverse search using the SauceNAO API.
        ///
        ///This bot was created by a third party to use SauceNAO on Telegram. The project has not any affiliation with Xamayon (the creator of SauceNAO)..
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this feature to block the reverse search of images sent by specific bots in your group chats.
        ///To add a bot to AntiCheat list, just reply to a message sent by the bot with &lt;code&gt;/anticheats add&lt;/code&gt;.
        ///To remove the bot, reply to the message with &lt;code&gt;/anticheats remove &lt;/code&gt;..
        /// </summary>
        internal static string Anticheats {
            get {
                return ResourceManager.GetString("Anticheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot @{0} was added to the AntiCheats list..
        /// </summary>
        internal static string AnticheatsAdded {
            get {
                return ResourceManager.GetString("AnticheatsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot @{0} already exists in AntiCheats list..
        /// </summary>
        internal static string AnticheatsAlreadyExists {
            get {
                return ResourceManager.GetString("AnticheatsAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot @{0} was removed from the AntiCheats list..
        /// </summary>
        internal static string AnticheatsDeleted {
            get {
                return ResourceManager.GetString("AnticheatsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot @{0} doesn&apos;t exist in the AntiCheats list..
        /// </summary>
        internal static string AnticheatsDoesNotExist {
            get {
                return ResourceManager.GetString("AnticheatsDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups, no cheating, my friend..
        /// </summary>
        internal static string AnticheatsMessage {
            get {
                return ResourceManager.GetString("AnticheatsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target user isn&apos;t a bot..
        /// </summary>
        internal static string AntiCheatsNotABot {
            get {
                return ResourceManager.GetString("AntiCheatsNotABot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re already supporting &lt;a href=&quot;https://www.patreon.com/saucenao&quot;&gt;Xamayon&lt;/a&gt; (the original creator of saucenao.com), then you can configure the bot to use your own API key to get your sauces instead of using shared API keys.
        ///&lt;code&gt;/apikey status&lt;/code&gt; - Check the status of your saved api key.
        ///&lt;code&gt;/apikey set &amp;lt;your api key&amp;gt;&lt;/code&gt; - Save your API Plus key. Don&apos;t use free API keys or it will cause problems for you.
        ///&lt;code&gt;/apikey delete&lt;/code&gt; - Delete your saved api key..
        /// </summary>
        internal static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saved api key has been deleted..
        /// </summary>
        internal static string ApiKeyDeleted {
            get {
                return ResourceManager.GetString("ApiKeyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! The Bot will use your API key from now on.
        ///To delete it, use &lt;i&gt;/apikey delete&lt;/i&gt;..
        /// </summary>
        internal static string ApiKeyNew {
            get {
                return ResourceManager.GetString("ApiKeyNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no api key configured..
        /// </summary>
        internal static string ApiKeyNone {
            get {
                return ResourceManager.GetString("ApiKeyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Bot is configured to use the follow api key:&lt;/b&gt;
        ///{0}.
        /// </summary>
        internal static string ApiKeyStatus {
            get {
                return ResourceManager.GetString("ApiKeyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SauceNao is very busy right now. Please try again later or try using /temp command.
        ///If this message appears frequently, please check the &lt;a href=&quot;{0}&quot;&gt;support chat&lt;/a&gt;..
        /// </summary>
        internal static string Busy {
            get {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contributions are used to pay for the bot&apos;s hosting and the shared account that we use to search for your sauces. If you have any other questions, ask in the support chat.
        ///- &lt;a href=&quot;https://www.buymeacoffee.com/eptagone&quot;&gt;Buy me a cookie!&lt;/a&gt;
        ///- &lt;b&gt;Bitcoin:&lt;/b&gt; &lt;a href=&quot;bitcoin:BC1Q0W43TPRJN80ZN248K7XLZTU7LVHKZGY6DAK8MT?label=MyCoffe&amp;message=Invite%20me%20for%20a%20coffee&quot;&gt;bc1q0w43tprjn80zn248k7xlztu7lvhkzgy6dak8mt&lt;/a&gt;
        ///- &lt;b&gt;Toncoin:&lt;/b&gt; &lt;a href=&quot;ton://transfer/EQC3SWZxs_4ive2aD-njns1KnB4S2RUgaxDKJ7X4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuyMeACookie {
            get {
                return ResourceManager.GetString("BuyMeACookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My creator is &lt;a href=&quot;tg://user?id=418909573&quot;&gt;Derek Nieves&lt;/a&gt;..
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to reply to an image file (image, GIF or a sticker).
        /// </summary>
        internal static string EmptyRequest {
            get {
                return ResourceManager.GetString("EmptyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert file to a supported file..
        /// </summary>
        internal static string FailedConvertFile {
            get {
                return ResourceManager.GetString("FailedConvertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating temporary link....
        /// </summary>
        internal static string GeneratingTmpUrl {
            get {
                return ResourceManager.GetString("GeneratingTmpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command only works in group chats..
        /// </summary>
        internal static string GroupsOnly {
            get {
                return ResourceManager.GetString("GroupsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me an image file (image, GIF or a sticker) to find it&apos;s sauce right now. (source)
        ///&lt;i&gt;If I&apos;m in a group, reply to an image with /sauce &lt;/i&gt;.
        ///Forward the media files you have searched along with their sauce via bot. More Info: &lt;code&gt;/help MyHistory&lt;/code&gt;.
        ///Use my Anti-Cheat feature in your groups when playing &quot;Guess the Character&quot;. More Info: &lt;code&gt;/help AntiCheats&lt;/code&gt;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send images with sauce from your recent history via bot.
        ///The history will be erased periodically. If you want to delete your history right now, type &lt;code&gt; /history clear&lt;/code&gt;..
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View search history.
        /// </summary>
        internal static string HistoryButton {
            get {
                return ResourceManager.GetString("HistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your history has been erased.
        ///Inline search results can take a few minutes to disappear because they are cached..
        /// </summary>
        internal static string HistoryErased {
            get {
                return ResourceManager.GetString("HistoryErased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This seems somewhat empty. Try to find some sauces..
        /// </summary>
        internal static string HistoryNone {
            get {
                return ResourceManager.GetString("HistoryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That doesn&apos;t look like a photo file..
        /// </summary>
        internal static string InvalidPhoto {
            get {
                return ResourceManager.GetString("InvalidPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not specified sufficient parameters to use this function..
        /// </summary>
        internal static string MissingParams {
            get {
                return ResourceManager.GetString("MissingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sauce found. Maybe try &lt;a href=&quot;{0}&quot;&gt;Google Reverse Search&lt;/a&gt; or &lt;a href=&quot;{1}&quot;&gt;Yandex&lt;/a&gt; instead? or see on &lt;a href=&quot;{2}&quot;&gt;SauceNAO website&lt;/a&gt; to see all the results..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command only works in private chats..
        /// </summary>
        internal static string PrivateChatsOnly {
            get {
                return ResourceManager.GetString("PrivateChatsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string ResultCharacter {
            get {
                return ResourceManager.GetString("ResultCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string ResultCharacters {
            get {
                return ResourceManager.GetString("ResultCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string ResultCreator {
            get {
                return ResourceManager.GetString("ResultCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string ResultMaterial {
            get {
                return ResourceManager.GetString("ResultMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string ResultPart {
            get {
                return ResourceManager.GetString("ResultPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string ResultTime {
            get {
                return ResourceManager.GetString("ResultTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string ResultYear {
            get {
                return ResourceManager.GetString("ResultYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this command to change the reply language in the current chat.
        ///Not all languages are available.
        ///&lt;b&gt;Syntax:&lt;/b&gt;
        ///&lt;code&gt;/setlang &lt;language code&gt; [-Force]&lt;/code&gt;
        ///Specify the optional [-Force] parameter to keep your language in any group regardless of the group&apos;s language..
        /// </summary>
        internal static string SetLang {
            get {
                return ResourceManager.GetString("SetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your language preferences have been saved..
        /// </summary>
        internal static string SetLangSaved {
            get {
                return ResourceManager.GetString("SetLangSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Usage Statistics&lt;/b&gt;
        ///{0} successful searches in the last 20 days.
        ///Used by {1} users.
        ///Used by {2} groups..
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Chat.
        /// </summary>
        internal static string SupportChat {
            get {
                return ResourceManager.GetString("SupportChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! Check your &lt;a href=&quot;{0}&quot;&gt;temp url&lt;/a&gt;..
        /// </summary>
        internal static string TemporalUrlDone {
            get {
                return ResourceManager.GetString("TemporalUrlDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search could not be performed. The file size is too large..
        /// </summary>
        internal static string TooBigFile {
            get {
                return ResourceManager.GetString("TooBigFile", resourceCulture);
            }
        }
    }
}
