//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SauceNAO.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SauceDirectory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SauceDirectory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SauceNao.Core.Resources.SauceDirectory", typeof(SauceDirectory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://anidb.net/perl-bin/animedb.pl?show=anime&amp;aid={0}.
        /// </summary>
        public static string AnidbAid {
            get {
                return ResourceManager.GetString("AnidbAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://anime-pictures.net/pictures/view_post/.
        /// </summary>
        public static string AnimePicturesId {
            get {
                return ResourceManager.GetString("AnimePicturesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bcy.net/.
        /// </summary>
        public static string BcyId {
            get {
                return ResourceManager.GetString("BcyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://deviantart.com/view/.
        /// </summary>
        public static string DA {
            get {
                return ResourceManager.GetString("DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://danbooru.donmai.us/post/show/.
        /// </summary>
        public static string DanbooruId {
            get {
                return ResourceManager.GetString("DanbooruId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drawr.net/show.php?id={0}.
        /// </summary>
        public static string DrawrId {
            get {
                return ResourceManager.GetString("DrawrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://e621.net/post/show/.
        /// </summary>
        public static string e621Id {
            get {
                return ResourceManager.GetString("e621Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gelbooru.com/index.php?page=post&amp;s=view&amp;id={0}.
        /// </summary>
        public static string GelbooruId {
            get {
                return ResourceManager.GetString("GelbooruId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/searchbyimage?image_url={0}.
        /// </summary>
        public static string GoogleImageSearch {
            get {
                return ResourceManager.GetString("GoogleImageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.imdb.com/title/.
        /// </summary>
        public static string ImdbId {
            get {
                return ResourceManager.GetString("ImdbId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://myanimelist.net/anime.php?.
        /// </summary>
        public static string MyAnimeList {
            get {
                return ResourceManager.GetString("MyAnimeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://nijie.info/view.php?id={0}.
        /// </summary>
        public static string NijieId {
            get {
                return ResourceManager.GetString("NijieId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pawoo.net/@.
        /// </summary>
        public static string PawooId {
            get {
                return ResourceManager.GetString("PawooId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.pixiv.net/member_illust.php?mode=medium&amp;illust_id={0}.
        /// </summary>
        public static string PixivId {
            get {
                return ResourceManager.GetString("PixivId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gimmeproxy.com/api/getProxy?.
        /// </summary>
        public static string ProxyList {
            get {
                return ResourceManager.GetString("ProxyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://chan.sankakucomplex.com/post/show/.
        /// </summary>
        public static string SankakuId {
            get {
                return ResourceManager.GetString("SankakuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://saucenao.com/.
        /// </summary>
        public static string SauceNAO {
            get {
                return ResourceManager.GetString("SauceNAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://saucenao.com/search.php?url={0}.
        /// </summary>
        public static string SauceNAOsearch {
            get {
                return ResourceManager.GetString("SauceNAOsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://seiga.nicovideo.jp/.
        /// </summary>
        public static string SeigaId {
            get {
                return ResourceManager.GetString("SeigaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tineye.com/search?.
        /// </summary>
        public static string TinEye {
            get {
                return ResourceManager.GetString("TinEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yande.re/post/show/.
        /// </summary>
        public static string YandereId {
            get {
                return ResourceManager.GetString("YandereId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yandex.com/images/search?url={0}&amp;rpt=imageview.
        /// </summary>
        public static string YandexUrl {
            get {
                return ResourceManager.GetString("YandexUrl", resourceCulture);
            }
        }
    }
}
